runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1

jobs:   
 build_run_sim:
  runner: AWS-runner
  type:
   build: hardware
  output:
   artifact:
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.xpr
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.cache
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.hw
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.ip_user_files
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.sim
    - /tools/Xilinx/Vivado/2020.1/workspace/project_ci_sim.srcs
  steps:
   - run:
      name: Download files
      command: |
       source /tools/Xilinx/Vivado/2020.1/settings64.sh
       vivado -mode tcl -source sim.tcl        
      type: miscellaneous    
workflows:
 complete-build-test:
  jobs:
   - build_run_sim
